# Generated by Django 2.0.4 on 2018-04-26 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medicine name', max_length=200)),
                ('producer', models.CharField(help_text='Medicine producer', max_length=100)),
                ('url', models.CharField(help_text='Medicine web url', max_length=1000)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(help_text='Medicine price')),
                ('count', models.IntegerField(help_text='Number of medicine units')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medicine category name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for particular medicine unit', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('s', 'Sold'), ('o', 'Ordered'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Medicine unit status', max_length=1)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.Medicine')),
            ],
            options={
                'ordering': ['medicine'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.MedicineCategory'),
        ),
    ]
