# Generated by Django 2.0.4 on 2018-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_medicine_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'medicine categories'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(help_text='Medicine price'),
        ),
    ]
